"""Initial migration - create all tables

Revision ID: 4dcd2c439e15
Revises: 295707bfebd4
Create Date: 2024-08-18 21:12:35.512163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcd2c439e15'
down_revision = '295707bfebd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###